
### Create new post
POST http://localhost:3000/posts
Content-Type: application/json

{
    "sender": "Elad",
    "content": "This is my first post!"
}


### Get All Posts
GET http://localhost:3000/posts