
### Create new post
POST http://localhost:3000/posts
Content-Type: application/json

{
    "sender": "Elad",
    "content": "This is my first post!"
}


### Get All Posts
GET http://localhost:3000/posts


### Get Post by ID
GET http://localhost:3000/posts/123456789



### Get Posts by Sender
GET http://localhost:3000/posts?sender=<sender_id>




# git add .
# git commit -m "Get Post by Sender endpoint"
# git push origin feature/zur/get-post-by-Sender

# git checkout -b feature/elad/get-post-by-id
# git add .
# git commit -m "Add get post by id endpoint"
# git push
